blenv:
  version: '1.1'

environments:
  default:
    blender: /Applications/Blender.app/Contents/MacOS/Blender
    env_file: .env
    addons:
      - object_cursor_array

project:
  addons:
    object_cursor_array:
      source: 'src/object_cursor_array'

  app_templates: {}
