blenv:
  version: '1'
environments:
  default:
    blender: /Applications/Blender.app/Contents/MacOS/Blender
    env_file: .env
    app_template: hello_app_template
package:
  output: ./dist
project:
  name: hello_app_template
  source: /Users/brad/Code/BlenderProjects/bl-env/examples/bl-hello-app-template/hello_app_template
