blenv:
  version: '1'

project:
  app_templates:
    hello_app_template:
      source: 'src/hello_app_template'
  addons: {}

environments:
  default:
    blender: /Applications/Blender.app/Contents/MacOS/Blender
    env_file: '.env'
    app_template: 'hello_app_template'
